# Generated by Django 5.1.7 on 2025-04-30 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articleimage',
            options={'verbose_name': 'Фото для статті', 'verbose_name_plural': 'Фото для статтей'},
        ),
    ]
